name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
   - name: Publish Image
     uses: matootie/github-docker@v3.0.0
     with:
        accessToken: ${{ github.token }}
        context: web/
        
