name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Publish Image
           uses: matootie/github-docker@v3.1.0
           with:
              accessToken: ${{ github.token }}
              context: web
              contextName: web/Dockerfile
              containerRegistry: true
